- hosts: localhost
  connection: local
  vars_files:
    - vars/pip.yml
#  vars_prompt:
#    - name: "hostname"
#      prompt: "Computer Hostname"
#      private: no
  tasks:
#    - name: set computer hostname
#      command: "{{ item }}"
#      become: yes
#      with_items:
#       - scutil --set ComputerName "{{ hostname }}"
#       - scutil --set HostName "{{ hostname }}"
#       - scutil --set LocalHostName "{{ hostname }}"
#       - defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string "{{ hostname }}"
#    - name: install homebrew
#      shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
#      args:
#        creates: /opt/homebrew/bin/brew
    - name: install XQuartz
      homebrew_cask: name=xquartz state=installed
    - name: install binaries
      command: /opt/homebrew/bin/brew bundle --file files/Brewfile
    - name: install apps
      command: /opt/homebrew/bin/brew bundle --file files/Brewfile.apps
    - name: install mas apps
      command: /opt/homebrew/bin/brew bundle --file files/Brewfile.mas
    - name: accept xcode license
      command: xcodebuild -license accept
      become: yes
    - name: install fonts
      command: /opt/homebrew/bin/brew bundle --file files/Brewfile.fonts
    - name: install python packages
      pip:
        name: "{{ python_packages }}"
        state: latest
    - name: set macos defaults
      script: files/.macos
    - name: set default shell to homebrew-installed bash
      user:
        name: "{{ ansible_env.USER }}"
        shell: /opt/homebrew/bin/bash
      become: yes
#    - name: install nix
#      shell: /bin/bash -c "$(curl -L https://nixos.org/nix/install)"
#      args:
#        creates: /nix/
    # Configure git
    - name: Set Git user name globally
      become: yes
      community.general.git_config:
        name: user.name
        value: "Blue Thunder Somogyi"
        scope: global
    - name: Set Git user email for a local repository
      become: yes
      community.general.git_config:
        name: user.email
        value: "bluethunder.somogyi@bastion.com"
        scope: global
    - name: Set Git Editor
      become: yes
      community.general.git_config:
        name: core.editor
        value: "vim"
#    - name: rustup-init
#      command: /opt/homebrew/bin/rustup-init --no-modify-path -y
    - debug:
        msg: "Now just setup DropBox, run 'mackup restore', and reboot"
